apiVersion: v1
kind: Service
metadata:
  name: audiobook-player--mysql
  labels:
    app: audiobook-player
    tier: database
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: audiobook-player
    tier: database
