apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobook-player--client
  labels:
    app: audiobook-player
    tier: client
spec:
  selector:
    matchLabels:
      app: audiobook-player
      tier: client
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: audiobook-player
        tier: client
    spec:
      containers:
        - image: nginx:alpine
          name: client
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: files
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-config
          configMap:
            name: client-nginx-config
        - name: files
          persistentVolumeClaim:
            claimName: audiobook-player--client-pvc
