apiVersion: v1
kind: Service
metadata:
  name: audiobook-player--client
  labels:
    app: audiobook-player
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: audiobook-player
    tier: client
  type: ClusterIP
