apiVersion: v1
kind: Service
metadata:
  name: audiobook-player--server
  labels:
    app: audiobook-player
    tier: server
spec:
  ports:
    - port: 4000
  selector:
    app: audiobook-player
    tier: server
  type: ClusterIP
