apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobook-player--server
  labels:
    app: audiobook-player
    tier: server
spec:
  selector:
    matchLabels:
      app: audiobook-player
      tier: server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: audiobook-player
        tier: server
    spec:
      containers:
        - name: server
          image: amaxsoftware/audiobook-player-server:latest
          env:
            - name: MYSQL_HOST
              value: "audiobook-player--mysql"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: audiobook-player--mysql-password-bc6ggk5g2t
                  key: password
            - name: MYSQL_DATABASE
              value: audiobooks
            - name: WEB_SERVICE_ROOT
              value: /api
            - name: WEB_SERVICE_PORT
              value: "4000"
            - name: FILE_STORAGE_BASE_URL
              value: "http://localhost/files"
          command: [ "node", "/app/index.js" ]
          ports:
            - containerPort: 4000
