apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}--database
  labels:
    app: {{ .Values.appName }}
    tier: database
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        tier: database
    spec:
      containers:
        - image: mysql:latest
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.database.rootPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.database.database }}
            - name: MYSQL_USER
              value: {{ .Values.database.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.database.password }}
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-init
          persistentVolumeClaim:
            claimName: {{ .Values.appName }}--database-init-pvc
        - name: mysql-data
          persistentVolumeClaim:
            claimName: {{ .Values.appName }}--database-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}--files
  labels:
    app: {{ .Values.appName }}
    tier: files
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      tier: files
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        tier: files
    spec:
      containers:
        - image: nginx:alpine
          name: files
          ports:
            - containerPort: 80
          volumeMounts:
            - name: media-files
              mountPath: /usr/share/nginx/html/files/
      volumes:
        - name: media-files
          persistentVolumeClaim:
            claimName: {{ .Values.appName }}--files-pvc
