apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.appName }}--gateway
spec:
  gatewayClassName: nginx
  listeners:

    # HTTP
    - name: http
      protocol: HTTP
      port: 80
      hostname: {{ .Values.gateway.host }}
      allowedRoutes:
        namespaces:
          from: Same

    # HTTPS
    - name: https
      protocol: HTTPS
      port: 443
      hostname: {{ .Values.gateway.host }}
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: {{ .Values.appName }}--gateway-tls
