apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.appName }}--gateway-httproute
spec:
  parentRefs:
    - name: {{ .Values.appName }}--gateway
  hostnames:
    - {{ .Values.gateway.host }}
  rules:

    # Client
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Values.appName }}--client
          port: 8080

    # Server / API
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: {{ .Values.appName }}--server
          port: 4000

    # Files
    - matches:
        - path:
            type: PathPrefix
            value: /files
      backendRefs:
        - name: {{ .Values.appName }}--files
          port: 8080
