apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.appName }}--database-init-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hostpath
  local:
    path: {{ .Values.pv.databaseInit.path }}
  nodeAffinity:
    {{ toYaml .Values.pv.nodeAffinity | nindent 4 }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.appName }}--database-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hostpath
  local:
    path: {{ .Values.pv.database.path }}
  nodeAffinity:
    {{ toYaml .Values.pv.nodeAffinity | nindent 4 }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.appName }}--files-pv
spec:
  capacity:
    storage: 250Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hostpath
  local:
    path: {{ .Values.pv.audiobookFiles.path }}
  nodeAffinity:
    {{ toYaml .Values.pv.nodeAffinity | nindent 4 }}
