apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.appName }}--database-init-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-hostpath
  volumeName: {{ .Values.appName }}--database-init-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.appName }}--database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-hostpath
  volumeName: {{ .Values.appName }}--database-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.appName }}--files-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
  storageClassName: local-hostpath
  volumeName: {{ .Values.appName }}--files-pv
