apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}--gateway-tls
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.gateway.tls.crt }}
  tls.key: {{ .Values.gateway.tls.key }}
